language: java

script: mvn clean install -P strict

jdk:
  - oraclejdk7
  - oraclejdk8

branches:
  only:
  - master

sudo: false
cache:
  directories:
    - $HOME/.m2

after_success:
  - mvn clean cobertura:cobertura coveralls:report